import XCTest
@testable import AnswerCaptureCore
final class StorageTests:XCTestCase{
 func testSHA256(){XCTAssertEqual(CaptureID.sha256(Data("abc".utf8)),"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")}
 func testScanAndManifestShape()throws{let d=Date(timeIntervalSince1970:0);let p=ScanPage(index:1,fileName:"x.jpg",relativePath:"AnswerCapture/id/x.jpg",width:1,height:2,sizeBytes:3,sha256:"a");let s=ScanRecord(id:"id",createdAt:d,storageMode:.appSandboxOrDocumentPicker,pages:[p]);let data=try WireCoding.encoder.encode(s);let json=String(decoding:data,as:UTF8.self);XCTAssertTrue(json.contains("answer-capture.scan.v1"));XCTAssertTrue(json.contains(#""androidUri":null"#));XCTAssertNotNil(json.range(of:#""createdAt":"[^"]+\.\d{3}"#,options:.regularExpression))}
 func testPendingRemainsUntilExplicitRemovalAndRejectMovesIt()async throws{let root=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString);let q=PendingUploadQueue(root:root);let item=PendingUpload(id:"capture-1",payload:Data("payload".utf8));try await q.enqueue(item);let first=try await q.listPending();XCTAssertEqual(first,[item]);try await q.removeAfterConfirmedSuccess("capture-1");let afterRemove=try await q.listPending();XCTAssertTrue(afterRemove.isEmpty);try await q.enqueue(item);try await q.reject(item);let afterReject=try await q.listPending();XCTAssertTrue(afterReject.isEmpty);XCTAssertTrue(FileManager.default.fileExists(atPath:root.appendingPathComponent("Rejected/capture-1.json").path))}
 func testLegacyPendingDefaultsToRemoteAndTerminalReasons()throws{let json=Data(#"{"id":"old","payload":"","createdAt":"1970-01-01T09:00:00.000+09:00"}"#.utf8);let item=try WireCoding.decoder.decode(PendingUpload.self,from:json);XCTAssertEqual(item.kind,.remoteCapture);XCTAssertTrue(PendingUploadQueue.isTerminalRejectionReason("empty_answer"));XCTAssertFalse(PendingUploadQueue.isTerminalRejectionReason("timeout"))}
 func testPendingCountLimitDoesNotDeleteExistingItems()async throws{let root=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString);let q=PendingUploadQueue(root:root);for index in 0..<PendingUploadQueue.maximumCount{try await q.enqueue(.init(id:"item-\(index)",payload:Data()))};do{try await q.enqueue(.init(id:"overflow",payload:Data()));XCTFail("Expected queue limit error")}catch let error as PendingQueueError{guard case let .limitExceeded(count, _)=error else{return XCTFail("Wrong queue error")};XCTAssertEqual(count,PendingUploadQueue.maximumCount+1)};let snapshot=try await q.status();XCTAssertEqual(snapshot.count,PendingUploadQueue.maximumCount)}
}
